In [57]:
import numpy as np
from numpy import random

In [ ]:


a = np.array([1,2,3,4])
a = np.array([[1,2,3],[4,5,6]])
# print(a.shape)
# print(a.shape)

print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [21]:
b = np.empty((4,4), dtype=int)
b = np.ones(4)
b = np.ones((4,4), dtype=int)
b = np.ones((3,3), dtype=str)
# b = np.zeros((3,3), dtype=str)
b = np.ones((3,3), dtype=bool)
# b = np.zeros((3,3), dtype=bool)
# print(b)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
c = np.array([1,2,3,4,5])
cd = c.copy() # the copy will not be affected by the changes made to the original array
c[0] = 3

dc = c.view() # the view will be affected by the changes made to the original array
print("original",c)
print("copy", cd)
print("view", dc)

original [3 2 3 4 5]
copy [1 2 3 4 5]
view [3 2 3 4 5]


In [ ]:
# # d = np.arange(1, 21)
# d = np.arange(2, 20, 2)
d = np.array([1,2,3,4,5,6,7,8,9])
d = d.reshape((3, 3)) # change the dimensions of the array
print(d)
# for x in d:
#     for y in x:
#         print(y, end=" ")

# for x in np.nditer(d):
#     print(x, end=" ")

# for x in np.nditer(d[:, ::3]):
#   print(x)

for idx, x in np.ndenumerate(d):
  print(idx, x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [ ]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b = a.reshape(-1)  # flattening the array
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# e = np.array([1,2,3,4,5])
# ed = np.array([6,7,8,9,10])
# de = np.concatenate((e, ed))
# print("concatenate ",de)
e = np.array([[1,2], [3,4]])
ed = np.array([[5,6],[7,8]])
de = np.concatenate((e, ed))
print(de)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# e = np.array([1,2,3,4,5])
# ed = np.array([6,7,8,9,10])
e = np.array([[1,2], [3,4]])
ed = np.array([[5,6],[7,8]])

de = np.stack((e,ed), axis=1)
print("stack ", de)

In [27]:
# e = np.array([1,2,3,4,5])
# ed = np.array([6,7,8,9,10])
e = np.array([[1,2], [3,4]])
ed = np.array([[5,6],[7,8]])
de = np.hstack((e,ed))
print(de)


[[1 2 5 6]
 [3 4 7 8]]


In [28]:
e = np.array([1,2,3,4,5])
ed = np.array([6,7,8,9,10])
e = np.array([[1,2], [3,4]])
ed = np.array([[5,6],[7,8]])
de = np.dstack((e,ed))
print(de)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [31]:
e = np.array([1,2,3,4,5])
ed = np.array([6,7,8,9,10])
# e = np.array([[1,2], [3,4]])
# ed = np.array([[5,6],[7,8]])
de = np.column_stack((e,ed))
print(de)


[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [32]:
f = np.array([1,2,3,4,5,6])
f = np.array([[1,2,3],[4,5,6]])
fe = np.array_split(f, 3)
for x in fe:
    print(x)

[[1 2 3]]
[[4 5 6]]
[]


In [4]:
f = np.array([1,2,19,45,23,3,4,5,6])
f.sort()
print(f)

[ 1  2  3  4  5  6 19 23 45]


In [5]:
f = np.array(["we","kj","ab","cd"])
f.sort()
print(f)

['ab' 'cd' 'kj' 'we']


In [8]:
f = np.array([[14,50,34],[13,2,3],[49,5,6]])
f.sort()
print(f)

[[14 34 50]
 [ 2  3 13]
 [ 5  6 49]]


In [ ]:
f = np.array([[14,50,34],[13,2,8],[49,5,6]])
print(f.min())
print("vertical ",f.min(axis=0)) # shows the min element from each column
print("horizontal ",f.min(axis=1)) # shows the min element from each row

2
vertical  [13  2  6]
horizontal  [14  2  5]


In [ ]:
f = np.array([1,2,4,3,5,6])
g = np.array([23,4,3,56,78])
fg = np.intersect1d(f,g)  # resultant array will be sorted
print(fg)

[3 4]


In [21]:
f = np.array([[14,50,34],[13,2,8],[49,5,6]])
g = np.array([[4,0,4],[13,2,8],[9,5,6]])
fg = np.intersect1d(f,g)  # resultant array will be sorted
print(fg)

[ 2  5  6  8 13]


In [24]:
f = np.array([1,2,4,3,5,6])
g = np.array([23,4,3,56,78])
fg = np.setdiff1d(f,g)
print(fg)

[1 2 5 6]


In [50]:
f = np.array([1,2,4,3,5,6])
g = np.array([1,2,3,4,5,6])
fgg = np.concatenate((f,g))
fg = np.sum(fgg, axis=0)
print(fg)

42


In [ ]:
f = np.array([1,2,4,3,5,6])
f = f + 10  # scalar operation
print(f)

[11 12 14 13 15 16]


In [52]:
f = np.array([1,2,4,3,5,6])
fg = np.mean(f)
print(fg)

3.5


In [54]:
f = np.array([1,20,4,3,5,6])
fg = np.median(f)
print(fg)

4.5


In [ ]:
f = np.array([1,2,4,3,5,6])
fg = np.std(f) # standard deviation
print(fg)

1.707825127659933


In [66]:
n = random.randint(10, size=4)
print(n)

[3 7 9 8]


In [75]:
f = np.array([1,2,4,3,5,6])
g = random.choice(f)
print(g)

4


In [76]:
f = np.array([1,2,4,3,5,6])
print(np.log2(f))

[0.         1.         2.         1.5849625  2.32192809 2.5849625 ]


In [ ]:
n = 12
m = 24
print("LCM ",np.lcm(n,m))
print("HCF or GCD",np.gcd(n,m))

LCM  24
HCF or GCD 12
