In [ ]:
import numpy as np

a = np.array([1,2,3,4])
a = np.array([[1,2,3],[4,5,6]])
# print(a.shape)
# print(a.shape)

print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [21]:
b = np.empty((4,4), dtype=int)
b = np.ones(4)
b = np.ones((4,4), dtype=int)
b = np.ones((3,3), dtype=str)
# b = np.zeros((3,3), dtype=str)
b = np.ones((3,3), dtype=bool)
# b = np.zeros((3,3), dtype=bool)
# print(b)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
c = np.array([1,2,3,4,5])
cd = c.copy() # the copy will not be affected by the changes made to the original array
c[0] = 3

dc = c.view() # the view will be affected by the changes made to the original array
print("original",c)
print("copy", cd)
print("view", dc)

original [3 2 3 4 5]
copy [1 2 3 4 5]
view [3 2 3 4 5]


In [69]:
# # d = np.arange(1, 21)
# d = np.arange(2, 20, 2)
d = np.array([1,2,3,4,5,6,7,8,9,10])
d = d.reshape((2, 5))
print(d)
# for x in d:
#     for y in x:
#         print(y, end=" ")

# for x in np.nditer(d):
#     print(x, end=" ")

# for x in np.nditer(d[:, ::3]):
#   print(x)

for idx, x in np.ndenumerate(d):
  print(idx, x)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [86]:
e = np.array([1,2,3,4,5])
ed = np.array([6,7,8,9, 10])
de = np.concatenate((e, ed))
print(de)
# e = np.array([[1,2], [3,4]])
# ed = np.array([[5,6],[7,8]])
# de = np.concatenate((e, ed), axis=1)
# print(de)

de = np.stack((e,ed), axis=1)
print(de)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [98]:
f = np.array([1,2,3,4,5,6])
fe = np.array_split(f, 2)
print(fe[0])
print(fe[1])

[1 2 3]
[4 5 6]
